site_name: AmbariDocs
theme: flatly
#theme: readable
#theme: readthedocs
pages:
- ['index.md', 'Home']
- ['delete-service.md', 'Guide', 'Delete a Service']
- ['ambari-shell.md', 'Guide', 'Use Ambari Shell']
- ['ambari-docker.md', 'Guide', 'Run Ambari as Docker Container']
- ['ambari-database.md', 'Guide', 'Connect to Server Database']
- ['ambari-design.md', 'Design']
- ['question-set.md', 'Questions']
